name: Lobo Greets

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "vflobo  first issue"
        pr-message: "Message that will be displayed on users' first pull request"
